version: '3.9'
services:
  mongodb:
    container_name: mongo
    image: "mongo:3.6.8"
    networks:
      - backend

    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  app:
    container_name: go
    build: .
    ports:
      - "8080:8090"
    links:
      - mongodb
    networks:
      - backend
volumes:
  data: 

networks:
  backend: 